### ISSUE TITLE
crear el fondo de la aplicación

### ISSUE THREAD

**Issue by JessCasasDev** [carmabol/angular-sessions#3]
crear el fondo de la aplicacion en app.component
![image](https://user-images.githubusercontent.com/15127221/176480317-c8921a9c-df03-4204-8fc3-c37d27c088fb.png)

**Comment by carmabol** [comment]
Estructura actualizada en el App Component Con el diseño del fondo con una clase container en el appComponent.css con un flex-direction Column
![image](https://user-images.githubusercontent.com/18455305/178085922-a28a1618-6552-45a8-b9f6-3c8b75aa351f.png)
