### ISSUE TITLE
agregar el titulo y el componente de claro/oscuro

### ISSUE THREAD

**Issue by JessCasasDev** [carmabol/angular-sessions#4]
Crear un contenedor que será quien contenga los items de la aplicacion en app.component
![image](https://user-images.githubusercontent.com/15127221/176480595-abac673b-d2ba-4356-a68c-7c32d225858a.png)
Crear el contenedor que tenga el titulo y el icono de sol/luna
![image](https://user-images.githubusercontent.com/15127221/176480701-b96ecc0c-1d29-4457-915a-68e054417cf5.png)
Crear el componente de sol/luna

**Comment by carmabol** [comment]
Elaborado el Componente VisualModeComponent con la funcionalidad de cambio de variable modo para el sol/luna

**Comment by JessCasasDev** [comment]
Actualizar para que el titulo tenga la misma apariencia que en la imagen y que la posicion de los elementos sea a los extremos del contenedor y que la imagen del sol/luna tenga las dimensiones adecuadas
![image](https://user-images.githubusercontent.com/15127221/178778420-019c6cd9-a279-4a6b-816c-0a9d98a1e1b4.png)
