### ISSUE TITLE
Crear la lista de TODOS

### ISSUE THREAD

**Issue by JessCasasDev** [carmabol/angular-sessions#6]
Crear un componente que será la lista de TODOs que el usuario verá, solo crear la parte visual 
![image](https://user-images.githubusercontent.com/15127221/176481206-bf0a702c-3af9-46f6-a6b9-1a055aa89b4f.png)

**Comment by carmabol** [comment]
Componente ListTodoComponent creado con las variables que visualizan el listado de items

**Comment by JessCasasDev** [comment]
Actualizar para que el componente tome la vista del proyecto 
![image](https://user-images.githubusercontent.com/15127221/178778847-65a43cd1-deab-400a-94b1-fcca32234259.png)
Pdta: si es posible, usar Grid para afianzar conocimientos de esta propiedad
