### ISSUE TITLE
Crear el componente de acciones

### ISSUE THREAD

**Issue by JessCasasDev** [carmabol/angular-sessions#7]
Crear el componente de acciones (solo lo visual) 
![image](https://user-images.githubusercontent.com/15127221/176481350-48095c04-fdca-45c5-8a90-3b76b61b5789.png)

**Comment by carmabol** [comment]
Se creó el componente ActionsTodoComponent para mostrar las opciones de las acciones

**Comment by JessCasasDev** [comment]
Actualizar para que el componente tome la vista que se requiere del proyecto 
![image](https://user-images.githubusercontent.com/15127221/178779113-edb9439a-8317-4124-ba4f-21323c0bcdee.png)
